# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c279bddc867c205cc81b1f6d0e9d7315d1a7531767d4733265b9894e59b9d87403067da77e26be566053d4a9279c2815e5a45370bd200adf86b13aee73d5021d

test:
  secret_key_base: 42ac138d1adbb6ca1a81f33e591b421a93cff8cfcd8d169634e873ff84b4795bb7116706cebe7964981956294ed078f044cf603bdc5b592cba60072463e0a74a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
